In [ ]:
# mengimpor tiga pustaka di Python yaitu NumPy, Matplotlib, dan Pandas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Membaca dataset dari file CSV dengan menggunakan Pandas.
dataset = pd.read_csv("837-pekerjaan.csv", sep=';')
dataset

No Jenis Pekerjaan    Gaji  Waktu Bekerja (dalam menit)  \
0      1          DOKTER  900000                          420   
1      2          DOKTER  500000                          600   
2      3          DOKTER  284204                          300   
3      4          DOKTER  900000                          360   
4      5          DOKTER  900000                          180   
..   ...             ...     ...                          ...   
832  833       SUPIR BIS  120000                          360   
833  834       PERTANIAN  280000                          300   
834  835       PERTANIAN  280000                          300   
835  836       PERTANIAN  280000                          460   
836  837         MEKANIK  600000                          420   

     Lama Bermain (dalam menit)   Kelas  
0                           780  Negeri  
1                           840  Negeri  
2                           360  Negeri  
3                           420  Negeri  
4                           240  Negeri  
..                          ...     ...  
832                         840   Buruh  
833                         300   Buruh  
834                         420   Buruh  
835                         720   Buruh  
836                         540  Swasta  

[837 rows x 6 columns]

In [ ]:
# melakukan encoding (penyandian) pada data kategori atau label menjadi bilangan bulat.
from sklearn.preprocessing import LabelEncoder

In [ ]:
# membuat objek LabelEncoder dari modul scikit-learn
enc = LabelEncoder()

In [ ]:
# melakukan encoding pada kolom 'Jenis Pekerjaan' dan 'Kelas' dalam dataset menggunakan suatu objek encoder, yang kemudian dapat
# digunakan untuk mengubah nilai-nilai kategorikal menjadi nilai numerik.
dataset['Jenis Pekerjaan'] = enc.fit_transform(dataset['Jenis Pekerjaan'].values)
dataset['Kelas'] = enc.fit_transform(dataset['Kelas'].values)

In [ ]:
dataset

No  Jenis Pekerjaan    Gaji  Waktu Bekerja (dalam menit)  \
0      1                0  900000                          420   
1      2                0  500000                          600   
2      3                0  284204                          300   
3      4                0  900000                          360   
4      5                0  900000                          180   
..   ...              ...     ...                          ...   
832  833                6  120000                          360   
833  834                4  280000                          300   
834  835                4  280000                          300   
835  836                4  280000                          460   
836  837                1  600000                          420   

     Lama Bermain (dalam menit)  Kelas  
0                           780      1  
1                           840      1  
2                           360      1  
3                           420      1  
4                           240      1  
..                          ...    ...  
832                         840      0  
833                         300      0  
834                         420      0  
835                         720      0  
836                         540      2  

[837 rows x 6 columns]

In [ ]:
# Menghapus kolom 'Jenis Pekerjaan' dari dataset dan menyimpannya ke dalam variabel
atr_dataset = dataset.drop(columns = 'Kelas')
atr_dataset

No  Jenis Pekerjaan    Gaji  Waktu Bekerja (dalam menit)  \
0      1                0  900000                          420   
1      2                0  500000                          600   
2      3                0  284204                          300   
3      4                0  900000                          360   
4      5                0  900000                          180   
..   ...              ...     ...                          ...   
832  833                6  120000                          360   
833  834                4  280000                          300   
834  835                4  280000                          300   
835  836                4  280000                          460   
836  837                1  600000                          420   

     Lama Bermain (dalam menit)  
0                           780  
1                           840  
2                           360  
3                           420  
4                           240  
..                          ...  
832                         840  
833                         300  
834                         420  
835                         720  
836                         540  

[837 rows x 5 columns]

In [ ]:
# Mengambil kolom "Kelas" dari DataFrame dataset dan menyimpannya dalam variabel cls_dataset.
cls_dataset = dataset ['Kelas']
cls_dataset

0      1
1      1
2      1
3      1
4      1
      ..
832    0
833    0
834    0
835    0
836    2
Name: Kelas, Length: 837, dtype: int64

In [ ]:
#  digunakan untuk mengimpor modul-modul yang dibutuhkan dari scikit-learn (sebuah pustaka machine learning di Python)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# membagi dataset menjadi data pelatihan (train) dan data uji (test) menggunakan train_test_split, dan
# kemudian melatih model Decision Tree pada data pelatihan (xtrain, ytrain)
xtrain, xtest, ytrain, ytest = train_test_split(atr_dataset, cls_dataset, test_size=0.4, random_state=1)
tree_dataset = DecisionTreeClassifier(random_state=1)
tree_dataset.fit(xtrain, ytrain)

DecisionTreeClassifier(random_state=1)

In [ ]:
#  melakukan prediksi menggunakan model pohon keputusan (C4.5) pada data pengujian (xtest), menghitung dan menampilkan confusion matrix,
# classification report (termasuk akurasi), serta tingkat akurasi dalam persentase.

y_pred = tree_dataset.predict(xtest)
cm = confusion_matrix(ytest, y_pred)
print("Confusion Matrix")
print(cm)
akurasi = classification_report(ytest, y_pred, zero_division=1)
print("Tingkat Akurasi Algoritma C4.5")
print("Akurasi :", akurasi)
akurasi = accuracy_score(ytest, y_pred)
print("Tingkat Akurasi : %d persen" %(akurasi*87))

Confusion Matrix
[[ 90   0   0]
 [  0 170   0]
 [  0   0  75]]
Tingkat Akurasi Algoritma C4.5
Akurasi :               precision    recall  f1-score   support

           0       1.00      1.00      1.00        90
           1       1.00      1.00      1.00       170
           2       1.00      1.00      1.00        75

    accuracy                           1.00       335
   macro avg       1.00      1.00      1.00       335
weighted avg       1.00      1.00      1.00       335

Tingkat Akurasi : 87 persen


In [ ]:
# menghasilkan file DOT yang merepresentasikan struktur pohon keputusan (decision tree) dari model yang telah dilatih menggunakan dataset (tree_dataset).
from sklearn.tree import export_graphviz
export_graphviz(tree_dataset, out_file="Tree_Kelas.dot", class_names=["Pegawai Buruh", "Pegawai Negeri", "Pegawai Swasta", "Polisi","Pertanian","Pedagang","Supir Bis","Trans"],
                feature_names=atr_dataset.columns, impurity=False, filled=True)

In [ ]:
# membaca dan menampilkan visualisasi pohon keputusan (dalam format DOT) yang disimpan dalam file "Tree_Kelas.dot" menggunakan perpustakaan Graphviz.

import graphviz

with open("Tree_Kelas.dot") as fig:
  dot_graph = fig.read()
  graph = graphviz.Source(dot_graph)

graph.view()

'Source.gv.pdf'